version: '3.8'

services:
  promptmcp:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "dist/health.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
