services:
  promptmcp-server:
    build:
      context: ..
      dockerfile: vibe/Dockerfile
    container_name: promptmcp-server
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ../config/openai-keys.env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ENHANCE_DEBUG=false
      - CONTEXT7_DEBUG=false
      - PORT=3000
      - HTTP_PORT=3001
      - WORKSPACE_PATH=/app
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=promptmcp_vectors
      - MCP_CONFIG_PATH=/app/config/mcp-config.json
      - CONTEXT7_API_KEY=ctx7sk-b6f0b8b1-c91f-4d1a-9d71-7a67e98c2e49
      - CONTEXT7_ENABLED=true
      - CONTEXT7_USE_HTTP_ONLY=true
      - CONTEXT7_BASE_URL=https://mcp.context7.com/mcp
      - CONTEXT7_CACHE_TTL=604800
      - PROMPT_ENHANCEMENT_ENABLED=true
      - PROMPT_ENHANCEMENT_STRATEGY_TYPE=general
      - PROMPT_ENHANCEMENT_MAX_TOKENS=2000
      - PROMPT_ENHANCEMENT_TEMPERATURE=0.3
      - PROMPT_ENHANCEMENT_QUALITY_THRESHOLD=0.8
      - PROMPT_ENHANCEMENT_COST_LIMIT=10.0
      - PROMPT_ENHANCEMENT_RATE_LIMIT=100
      - PROMPT_ENHANCEMENT_FALLBACK_ENABLED=false
      # Temperature Optimization Settings
      - OPENAI_TEMPERATURE_TASK_BREAKDOWN=0.4
      - OPENAI_TEMPERATURE_COMPLEXITY_ANALYSIS=0.1
      - OPENAI_TEMPERATURE_PROMPT_ENHANCEMENT=0.6
      - OPENAI_TEMPERATURE_SUMMARIZATION=0.3
      - OPENAI_TEMPERATURE_CONNECTION_TEST=0.1
      # Model Selection
      - OPENAI_MODEL_PRIMARY=gpt-4o
      - OPENAI_MODEL_FALLBACK=gpt-4o-mini
      - OPENAI_MODEL_COMPLEX=gpt-4o
      - OPENAI_MODEL_SIMPLE=gpt-4o-mini
      - OPENAI_MODEL_TEST=gpt-4o-mini
      # Cost Monitoring
      - OPENAI_DAILY_COST_LIMIT=5.0
      - OPENAI_MONTHLY_COST_LIMIT=50.0
      - OPENAI_PER_REQUEST_COST_LIMIT=1.0
      # Debug Settings
      - DEBUG_TEMPERATURE=false
      - DEBUG_PROMPTS=false
      - DEBUG_COSTS=false
      - DEBUG_MODELS=false
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../mcp-config.json:/app/config/mcp-config.json:ro
    depends_on:
      - qdrant
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  qdrant_data: