services:
  promptmcp-server:
    build:
      context: ..
      dockerfile: vibe/Dockerfile
    container_name: promptmcp-server
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - ENHANCE_DEBUG=true
      - CONTEXT7_DEBUG=true
      - PORT=3000
      - HTTP_PORT=3001
      - WORKSPACE_PATH=/app
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=promptmcp_vectors
      - MCP_CONFIG_PATH=/app/config/mcp-config.json
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../mcp-config.json:/app/config/mcp-config.json:ro
    depends_on:
      - qdrant
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  qdrant_data: