services:
  promptmcp-server:
    build:
      context: ..
      dockerfile: vibe/Dockerfile
    container_name: promptmcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CONTEXT7_API_KEY=${CONTEXT7_API_KEY:-}
      - CONTEXT7_USE_HTTP_ONLY=true
      - CONTEXT7_CHECK_COMPATIBILITY=false
      - CONTEXT7_ENABLED=true
      - LOG_LEVEL=info
      - PORT=3000
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  qdrant_data: